### ISSUE TITLE
Fails for huge JSON documents

### ISSUE THREAD

**Issue by cristim** [zgrossbart/jdd#1] opened 2016-12-11 10:28 UTC
I tried to compare
https://raw.githubusercontent.com/powdahound/ec2instances.info/f34075aa09c52233735cd879ebda3f70d77b7ca5/www/instances.json
with
https://raw.githubusercontent.com/powdahound/ec2instances.info/ac8f6729ba24df485e42395941045d827be2a67d/www/instances.json

It reports the files as identical (they ovbiously aren't), and the following error shows up in the JS Console:
`jdd.js:387 Uncaught Unable to find line number for(The right side of this object has more items than the left side): ///60`

**Comment by zgrossbart** [comment] 2016-12-11 13:39
Hello Cristian,

Thank you for trying out my JSONDiff tool.  I tried your two files and I see the same problem that you do.  Unfortunately, I don't think there is a way to fix this.  Your files are very large (about 1.2 MB).  I can't even paste them into pro.jsonlint.com without the browser crashing.

The error message you got is not ideal, but fundamentally the issue is that you ran out of browser memory.  Parsing and analyzing JavaScript files like this in the browser just isn't ideal.  I could imagine writing a program in Java or C++ (maybe NodeJS) that could parse and analyze this files much faster and without any UI, but that would be a different program than JSONDiff.

If you just can about these two files instead of the larger problem I suggest you try cutting the files into quarters to compare them.  It might make them small enough and help you find the difference.

Good luck.

**Comment by zgrossbart** [comment] 2016-12-11 13:40
I'm going to close this issue since it is outside of the goals of this project.

**Closed by zgrossbart** 2016-12-11 13:40 UTC
